# Dockerfile
# 1st Stage
FROM node:17 AS builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json .
COPY yarn.lock .
RUN npm install 
COPY . .
RUN npm run build
# 2nd Stage
FROM nginx:1.21-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# reverse proxy config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]